### ISSUE TITLE
多变量混合解析

### ISSUE THREAD

**Issue by zjz19901029** [xuqiang521/xuejs#1]
现在对类似`<div>{{tel}}{{name}}</div><div>电话：{{tel}}</div>`这种貌似没办法解析，想请教下有没有什么好的方法和思路。

**Comment by xuqiang521** [comment]
[parseText](https://github.com/vuejs/vue/blob/dev/dist/vue.js#L7948)
[parseModel](https://github.com/vuejs/vue/blob/dev/dist/vue.js#L5888)

 #1 fixed in 82d62c312a85cedb4da8c6e9c85a7c8e2a29995a

**Comment by xuqiang521** [comment]
#1 fixed in 82d62c312a85cedb4da8c6e9c85a7c8e2a29995a
